name: Packer Build and Go test after Pull Request

on:
  push:
    branches:
      - main

jobs:
  after_pull_rq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Get location
        run: pwd

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./test
      
      - name: Build webapp executable file
        run: GOOS=linux GOARCH=amd64 go build -o webapp
      
      - name: Initialize packer
        run: packer init webapp_ami_packer.pkr.hcl
      
      - name: Build AMI with Packer
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "instance_type=${{ secrets.INSTANCE_TYPE }}" \
            -var "ssh_username=${{ secrets.SSH_USER }}" \
            -var "ami_user=${{ secrets.AMI_USER }}" \
            -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
            -var "ami_name=${{ secrets.AMI_NAME }}" \
            webapp_ami_packer.pkr.hcl
