name:  Packer validate on Pull Request

on:
  workflow_dispatch:

jobs:
  packer_validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main
      
      - name: Format packer
        run: packer init webapp_ami_packer.pkr.hcl

      - name: Format packer
        run: packer fmt webapp_ami_packer.pkr.hcl
      
      - name: Validate packer
        run: |
          packer validate \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "instance_type=${{ secrets.INSTANCE_TYPE }}" \
            -var "ssh_username=${{ secrets.SSH_USER }}" \
            -var "ami_user=${{ secrets.AMI_USER }}" \
            -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
            -var "ami_name=${{ secrets.AMI_NAME }}" \
            -var "mysql_pwd=${{ secrets.DB_PWD }}" \
            webapp_ami_packer.pkr.hcl
      
      - name: Run Go tests
        run: go test ./test

        